# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
  body = """
{% if version %}\
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
## [unreleased]{% endif %}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for scope, scoped_commits in commits | group_by(attribute="scope") %}
{% if scope %}
#### {{ scope | upper_first }}{% endif %}
{% for commit in scoped_commits %}
- {% if commit.breaking %}[**breaking**] {% endif %}[{{ commit.message | upper_first }}](https://github.com/scarcekoi/pride-flags/commit/{{ commit.id }}){% endfor %}{% endfor %}
{% endfor %}
"""
  trim = true
  render_always = true
  link_commits = true
  commit_url = "https://github.com/scarcekoi/pride-flags/commit/{{hash}}"

[git]
  conventional_commits = true
  filter_unconventional = false
  protect_breaking_commits = false
  commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->🚀 Features" },
    { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
    { message = "^doc", group = "<!-- 3 -->📚 Documentation" },
    { message = "^perf", group = "<!-- 4 -->⚡ Performance" },
    { message = "^refactor", group = "<!-- 2 -->🚜 Refactor" },
    { message = "^style", group = "<!-- 5 -->🎨 Styling" },
    { message = "^test", group = "<!-- 6 -->🧪 Testing" },
    { message = "^ci", group = "<!-- 11 -->⚙️ CI/CD" },
    { message = "^merge:", group = "<!-- 12 -->🔀 Merges" },
    { message = "^chore\\(release\\): prepare for", skip = true },
    { message = "^chore\\(deps.*\\)", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },
    { message = "^chore", group = "<!-- 7 -->⚙️ Chores" },
    { body = ".*security", group = "<!-- 8 -->🛡️ Security" },
    { message = "^revert", group = "<!-- 9 -->◀️ Revert" },
    { message = ".*", group = "<!-- 10 -->💼 Other" },
  ]
  topo_order = true
  sort_commits = "oldest"
