name: Update Changelog

on:
  push:
    branches:
      - master

jobs:
  regenerate-changelog:
    runs-on: codeberg-medium
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install git-cliff
        run: |
          curl -L "https://github.com/orhun/git-cliff/releases/download/v2.12.0/git-cliff-2.12.0-x86_64-unknown-linux-gnu.tar.gz" -o git-cliff.tar.gz
          tar -xzf git-cliff.tar.gz --strip-components=1
          chmod +x git-cliff
          mv git-cliff /usr/local/bin/
          git-cliff --version

      - name: Generate CHANGELOG.md
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          git-cliff -o CHANGELOG.md

      - name: Commit and push changelog
        env:
          GIT_AUTHOR_NAME: "forgejo-actions"
          GIT_AUTHOR_EMAIL: "forgejo-actions@users.noreply.local"
        run: |
          git config user.name "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"
          git add CHANGELOG.md
          git diff --cached --quiet || git commit -m "chore(changelog): regenerate data"
          git push
