name: Create Release

on:
  push:
    tags:
      - "*" # triggers on any tag push

jobs:
  release:
    runs-on: codeberg-small
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip python3 python3-yaml
          cargo install codeberg-cli

      - name: Install git-cliff
        run: |
          curl -L "https://github.com/orhun/git-cliff/releases/download/v2.12.0/git-cliff-2.12.0-x86_64-unknown-linux-gnu.tar.gz" -o git-cliff.tar.gz
          tar -xzf git-cliff.tar.gz --strip-components=1
          chmod +x git-cliff
          mv git-cliff /usr/local/bin/
          git-cliff --version

      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "Latest tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create zip files for themes
        run: |
          THEMES=(mocha macchiato frappe latte)
          for theme in "${THEMES[@]}"; do
            zip -r "${theme}.zip" "themes/$theme"
          done

      - name: Generate changelog
        id: changelog
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0)
          PREV_TAG=$(git describe --tags --abbrev=0 $LATEST_TAG^)
          git-cliff --tag "$PREV_TAG..$LATEST_TAG" > changelog.md
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          cat changelog.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create release
        env:
          FJ_API_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
        run: |
          TAG="${{ steps.get_tag.outputs.tag }}"
          berg release create \
            --repo "scarcekoi/pride-flags" \
            --tag "$TAG" \
            --name "$TAG" \
            --description "${{ steps.changelog.outputs.changelog }}" \
            --assets "mocha.zip" \
            --assets "macchiato.zip" \
            --assets "frappe.zip" \
            --assets "latte.zip" \
            --assets flag_zips/*.zip
