name: Size Change
description: Request a size change for an existing flag
title: "[Flag]"
body:
  - id: change
    type: textarea
    attributes:
      label: The Change
      description: What size you want the flag changed to.
    validations:
      required: true
  - id: additional_comments
    type: textarea
    attributes:
      label: Any additional comments?
      description: Add any information that hasn't been covered in the previous sections!
