when:
  - event: push
    branch: master

clone:
  git:
    image: alpine/git
    settings:
      depth: 100
      lfs: false

steps:
  - name: regenerate-changelog
    image: debian:stable-slim
    environment:
      GIT_AUTHOR_NAME: forgejo-actions
      GIT_AUTHOR_EMAIL: forgejo-actions@users.noreply.local
    commands:
      - apt-get update
      - apt-get install -y curl git tar gzip

      - curl -L "https://github.com/orhun/git-cliff/releases/download/v2.12.0/git-cliff-2.12.0-x86_64-unknown-linux-gnu.tar.gz" -o git-cliff.tar.gz
      - tar -xzf git-cliff.tar.gz --strip-components=1
      - chmod +x git-cliff
      - mv git-cliff /usr/local/bin/
      - git-cliff --version

      - TAG=$(git describe --tags --abbrev=0)
      - echo "Latest tag: $TAG"

      - git-cliff -o CHANGELOG.md

      - git config user.name "$GIT_AUTHOR_NAME"
      - git config user.email "$GIT_AUTHOR_EMAIL"

      - git add CHANGELOG.md
      - |
        if ! git diff --cached --quiet; then
          git commit -m "chore(changelog): regenerate data"
          git push origin master
        fi

  - name: regenerate-release-files
    image: debian:stable-slim
    depends_on:
      - regenerate-changelog
    environment:
      GIT_AUTHOR_NAME: forgejo-actions
      GIT_AUTHOR_EMAIL: forgejo-actions@users.noreply.local
    commands:
      - apt-get update
      - apt-get install -y git zip curl

      - mkdir -p dist/release/flags
      - mkdir -p dist/release/flavours

      - THEMES="mocha macchiato frappe latte"

      - |
        for theme in $THEMES; do
          zip -r "dist/release/flavours/${theme}.zip" "themes/$theme"/* -x "*.DS_Store"
        done

      - |
        curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
        chmod +x /usr/local/bin/yq

      - FLAGS=$(yq -r '.flags | keys[]' resources/flags.yml)

      - |
        for flag in $FLAGS; do
          ZIP_FILE="dist/release/flags/${flag}.zip"
          rm -f "$ZIP_FILE"

          for theme in $THEMES; do
            THEME_FLAG_DIR="themes/$theme/$flag"
            if [ -d "$THEME_FLAG_DIR" ]; then
              zip -r "$ZIP_FILE" "$THEME_FLAG_DIR" -x "*.DS_Store"
            fi
          done
        done

      - git config user.name "$GIT_AUTHOR_NAME"
      - git config user.email "$GIT_AUTHOR_EMAIL"

      - git add dist/release/*
      - |
        if ! git diff --cached --quiet; then
          git commit -m "chore(release-files): regenerate data"
          git fetch origin master
          git rebase origin/master
          git push origin master
        fi
